### ISSUE TITLE
原始微信小程序项目引入组件报错

### ISSUE THREAD

**Issue by Dovahkinn** [Chaunjie/kai-ui#24]
### 操作步骤：
1.  把 minicomponent 目录下的 toptips 目录拷贝到小程序项目的components目录下
1.  按照文档在pages目录下的文件中引入
```
// index.json
{
  "usingComponents": {
    "dialog": "/components/dialog-wxapp/dialog",
    "k-toptips": "/components/toptips/index"
  }
}

// index.wxml
<k-toptips id="toptips"/>
<view>
  ...
</view>

// index.js
import Toptips from '../../components/toptips/index';
Page({
...
})
```

3.  保存，预览
```
Mon Mar 25 2019 16:07:12 GMT+0800 (中国标准时间) Page 注册错误
VM2619:1 Please do not register multiple Pages in pages/index/index.js
console.error @ VM2619:1
T @ WAService.js:1
bt @ WAService.js:1
Rt @ WAService.js:1
(anonymous) @ index.js:3
require @ WAService.js:1
(anonymous) @ VM2634:20
scriptLoaded @ appservice?t=1553501232052:1217
script.onload @ appservice?t=1553501232052:1229
VM2619:1 thirdScriptError 
 sdk uncaught third Error 
 APP-SERVICE-Engine:Please do not register multiple Pages in pages/index/index.js 
 Error: APP-SERVICE-Engine:Please do not register multiple Pages in pages/index/index.js
    at bt (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:993244)
    at Rt (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:1007653)
    at http://127.0.0.1:16390/appservice/pages/index/index.js:9:1
    at require (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:1014710)
    at <anonymous>:20:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:16390/appservice/appservice?t=1553501232052:1217:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:16390/appservice/appservice?t=1553501232052:1229:20)
console.error @ VM2619:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1553501232052:1176
window.onerror @ VM2619:1
scriptLoaded @ appservice?t=1553501232052:1217
script.onload @ appservice?t=1553501232052:1229
VM2619:1 jsEnginScriptError
Component is not found in path "components/toptips/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "components/toptips/index" (using by "pages/index/index")
    at e (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:884653)
    at e (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:884839)
    at http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:900292
    at Object.t.addView (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:900838)
    at Function.value (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:980225)
    at kt (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:996594)
    at It (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:1000072)
    at Function.<anonymous> (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:1001080)
    at Be.<anonymous> (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:973438)
    at Be.emit (http://127.0.0.1:16390/appservice/__dev__/WAService.js:1:333476)
```
###  项目结构
![avatar](https://img-store-yanhaog.oss-cn-beijing.aliyuncs.com/%E6%8D%95%E8%8E%B7.PNG)

**Comment by Chaunjie** [comment]
@Dovahkinn 你先把你这个项目从开发者工具移除，然后重新添加下。

**Comment by Dovahkinn** [comment]
emmm, 可以了，非常感谢
